http://localhost:8080/view/teacher/mainpage
http://localhost:8080/view/teacher/schedule
http://localhost:8080/view/teacher/remark
http://localhost:8080/view/teacher/grade
http://localhost:8080/view/teacher/attendance
http://localhost:8080/view/teacher/schoolclass




